server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    #声明⾃⼰是个服务端
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false
